routes/todo.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.todo import Todo

# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性


# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('todo', __name__)


@main.route('/')
def index():
    # 查找所有的 todo 并返回
    todo_list = Todo.all()
    # flask 已经配置好了 jinja2 模板引擎
    # 并且可以直接使用 render_template 来生成响应数据(http_response)
    return render_template('todo_index.html', todos=todo_list)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    t = Todo.new(form)
    t.save()
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 todo
    return redirect(url_for('todo.index'))


@main.route('/delete/<int:todo_id>/')
def delete(todo_id):
    """
    <int:todo_id> 的方式可以匹配一个 int 类型
    int 指定了它的类型，省略的话参数中的 todo_id 就是 str 类型

    这个概念叫做 动态路由
    意思是这个路由函数可以匹配一系列不同的路由

    动态路由是现在流行的路由设计方案
    """
    # 通过 id 删除 todo
    t = Todo.delete(todo_id)
    # 引用蓝图内部的路由函数的时候，可以省略名字只用 .
    # 因为我们就在 todo 这个蓝图里面, 所以可以省略 todo
    # return redirect(url_for('todo.index'))
    return redirect(url_for('.index'))

templates/todo_index.html
<html>
<head>
    <title>Todo</title>
    <!-- 静态文件放在 /static 文件夹中 -->
    <!-- 引用路径是 /static/... -->
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <style type="text/css">
    .todo-table {
        margin: 0 auto;
    }
    .center {
        text-align: center;
    }



    </style>
</head>

<body>
<div class="center">
    <h1>Todo</h1>
    <!-- 注意这里 的 url_for 也是需要加上蓝图名字前缀的 -->
    <form action={{ url_for(
    "todo.add") }} method="post">
    <input type="text" placeholder="Add Todo" name="title">
    <input class="pure-button pure-button-primary" type="submit" value="Add">
    </form>
</div>

<table class="todo-table pure-table pure-table-horizontal pure-table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th>Title</th>
        <th>Time</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {% for t in todos %}
    <tr>
        <td>{{ t.id }}</td>
        <td>{{ t.title }}</td>
        <td>{{ t.ct }}</td>
        <!-- url_for 可以传递参数，先匹配动态路由，如果动态路由匹配失败则变成 query 参数 -->
        <td><a href={{ url_for('todo.delete', todo_id=t.id) }}>delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>